require 'settings'
require 'plugins'
require 'plugins.nvim-tree'
require 'plugins.lualine'
require 'plugins.bufferline'
require 'plugins.telekasten'
require 'colors.gruvbox'
require 'mappings'
require 'lsp'
require 'lsp.cmp'
require'colorizer'.setup()
