#! /bin/sh

$HOME/.config/polybar/launch.sh
pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --restore &
picom --experimental-backends -b &
dunst &
nm-applet &

bspc monitor -d I II III IV V VI 

bspc config border_width         3
bspc config window_gap          15
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Window rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config normal_border_color		"#302D41"
bspc config active_border_color		"#d5c4a1"
bspc config focused_border_color	"#F5C2E7"
bspc config presel_feedback_color	"#161320"
