#! /bin/sh

$HOME/.config/polybar/launch.sh
pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --restore &
picom --experimental-backends -b &
dunst &
lxsession &
# nm-applet &

bspc monitor -d 1 2 3 4 5 6 7 8 9 

bspc config focus_follows_pointer true
bspc config border_width         3
bspc config window_gap          30
bspc config split_ratio          0.58
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Window rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config normal_border_color		"#282828"
bspc config active_border_color		"#928374"
bspc config focused_border_color	"#b16286"
bspc config presel_feedback_color	"#282828"
